#This one uses only OS vertices (use for newer prods past 0903)
chi2:
    name: DummyMinChi2ScoutingRDF
    path: modules.muonsv_selection
    parameters:
        year: self.config.year

#Use this one for Scouting production before and including prod_0903
#chi2:
#    name: DummyMinChi2RDF
#    path: modules.muonsv_selection
#    parameters:
#        year: self.config.year

#bdt_inference_a:
#    name: DQCDULBDTNoJet
#    path: DQCD.Modules.BDTULinferenceNoJet
#    parameters:
#        isMC: self.dataset.process.isMC
#        scenario: A
#        bdt_name: bdt_scenarioA_nojetsel
