#yaml for the analysis workflow using our muonSV collections and BDT
muon:
    name: DQCDMuonSelectionScoutingRDF
    path: modules.muon_selection
    parameters:
        year: self.config.year


muonsv:
    name: DQCDMuonSVSelectionScoutingRDF
    path: modules.muonsv_selection
    parameters:
        gen_mass: 2


#Change name to DQCDScoutingTestBDT for parking trained BDT on Scouting data
#DQCDScoutingBDT is the scouting version
bdt_inference_a:
    name: DQCDScoutingBDT
    path: DQCD.Modules.BDTULinference
    parameters:
        isMC: self.dataset.process.isMC
        scenario: A


#These are for cutflows
#bdt_selection_vloose:
#    name: DQCDBDTSelectionRDF
#    path: modules.bdt_selection
#    parameters:
#        bdt_name: bdt_scenarioA
#        bdt_cut_value: 0.3 

#bdt_selection_loose:
#    name: DQCDBDTSelectionRDF
#    path: modules.bdt_selection
#    parameters:
#        bdt_name: bdt_scenarioA
#        bdt_cut_value: 0.6 

#bdt_selection_medium:
#    name: DQCDBDTSelectionRDF
#    path: modules.bdt_selection
#    parameters:
#        bdt_name: bdt_scenarioA
#        bdt_cut_value: 0.7 

#bdt_selection_tight:
#    name: DQCDBDTSelectionRDF
#    path: modules.bdt_selection
#    parameters:
#        bdt_name: bdt_scenarioA
#        bdt_cut_value: 0.98 

#trig:
#    name: DQCDTriggerSelectionRDF
#    path: modules.muonsv_selection
#    parameters:
#        gen_mass: 2

